server:
  port: 8080
  servlet:
    context-path: /spot-on

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spot_on_db
    username: root
    password: 1234

jwt:
  signerKey : "12345678901234567890123456789012"

pagination:
  page-size : 5