server:
  port: 8080
  servlet:
    context-path: /spot-on

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spot_on_db
    username: root
    password: 1234

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: buixuanphat.2704@gmail.com
    password: tszyeupgbyekncoj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "12345678901234567890123456789012"

pagination:
  page-size: 5


VNPay:
  vnp_TmnCode: "LDM0Y75F"
  vnp_HashSecret: "ZDDLMEIM13ZUCF84IMT11JTORQ10U4LC"
  vnp_PayUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  vnp_Returnurl: "https://jettie-unpadlocked-stoutly.ngrok-free.dev/spot-on/vnpay/return"